name: Build ARM64 Fedora bootc for Raspberry Pi 5

on:
  push:
    branches: [ main, develop ]
    tags: [ 'v*' ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

env:
  REGISTRY: quay.io
  IMAGE_NAME: tempest-concorde/fedora-bootc-rpi5

jobs:
  build-container:
    runs-on: ubuntu-24.04-arm64
    permissions:
      contents: read
      packages: write

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Log in to Container Registry
      uses: docker/login-action@v3
      with:
        registry: ${{ env.REGISTRY }}
        username: ${{ secrets.QUAY_USERNAME }}
        password: ${{ secrets.QUAY_TOKEN }}

    - name: Extract metadata
      id: meta
      uses: docker/metadata-action@v5
      with:
        images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
        tags: |
          type=ref,event=branch
          type=ref,event=pr
          type=semver,pattern={{version}}
          type=semver,pattern={{major}}.{{minor}}
          type=raw,value=latest,enable={{is_default_branch}}

    - name: Build and push container image
      uses: docker/build-push-action@v5
      with:
        context: .
        platforms: linux/arm64
        push: true
        tags: ${{ steps.meta.outputs.tags }}
        labels: ${{ steps.meta.outputs.labels }}
        cache-from: type=gha
        cache-to: type=gha,mode=max

  test-container:
    runs-on: ubuntu-24.04-arm64
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Build test image
      uses: docker/build-push-action@v5
      with:
        context: .
        platforms: linux/arm64
        push: false
        tags: fedora-bootc-rpi5:test
        cache-from: type=gha

    - name: Test container lint
      run: |
        docker run --rm --platform=linux/arm64 fedora-bootc-rpi5:test bootc container lint

    - name: Test container functionality
      run: |
        # Test that required packages are installed
        docker run --rm --platform=linux/arm64 fedora-bootc-rpi5:test \
          rpm -q tailscale NetworkManager-wifi podman
        
        # Test that scripts are executable
        docker run --rm --platform=linux/arm64 fedora-bootc-rpi5:test \
          test -x /usr/local/bin/wifi-setup.sh
        
        docker run --rm --platform=linux/arm64 fedora-bootc-rpi5:test \
          test -x /usr/local/bin/tailscale-setup.sh
        
        # Test that node-exporter container config exists
        docker run --rm --platform=linux/arm64 fedora-bootc-rpi5:test \
          test -f /etc/containers/systemd/node-exporter.container