name: Build and Test ARM64 Fedora bootc for Raspberry Pi 5

on:
  pull_request:
    branches: [ main ]
  workflow_dispatch:

env:
  REGISTRY_USER: rh-ee-chbutler
  IMAGE_REGISTRY: quay.io
  IMAGE: flightradar-bootc-pi

jobs:
  build-and-test:
    runs-on: ubuntu-24.04-arm
    container:
      image: registry.access.redhat.com/ubi9/ubi
      options: --privileged    
    permissions:
      contents: read
      packages: read

    steps:
    - name: Get container tools in UBI builder
      run: dnf -y install podman buildah skopeo make wget git

    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Workaround open podman-login action issue
      env:
        auth: "{ \"auths\": {} }"
      run: |
        mkdir -p $HOME/.docker
        echo $auth > $HOME/.docker/config.json

    - name: Build container image (no push)
      id: build-image
      uses: redhat-actions/buildah-build@v2
      with:
        image: "${{ env.IMAGE }}"
        tags: test ${{ github.sha }}
        platforms: linux/arm64
        containerfiles: |
          ./Containerfile

    - name: Test container lint
      run: |
        podman run --rm --platform=linux/arm64 ${{ env.IMAGE }}:test bootc container lint

    - name: Test container functionality
      run: |
        # Test that required packages are installed
        podman run --rm --platform=linux/arm64 ${{ env.IMAGE }}:test \
          rpm -q tailscale NetworkManager-wifi podman
        
        # Test that scripts are executable
        podman run --rm --platform=linux/arm64 ${{ env.IMAGE }}:test \
          test -x /usr/local/bin/wifi-setup.sh
        
        podman run --rm --platform=linux/arm64 ${{ env.IMAGE }}:test \
          test -x /usr/local/bin/tailscale-setup.sh
        
        # Test that node-exporter container config exists
        podman run --rm --platform=linux/arm64 ${{ env.IMAGE }}:test \
          test -f /etc/containers/systemd/node-exporter.container